# Generated by Django 4.2.2 on 2023-07-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channelsubscription_subscriber_and_more'),
        ('comment', '0002_remove_comment_user_remove_likedcomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_channel', to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='likedcomment',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
        ),
    ]
