# Generated by Django 4.2.2 on 2023-08-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
        migrations.AlterField(
            model_name='link',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
