# Generated by Django 4.2.2 on 2023-08-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_link_options_alter_link_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['position']},
        ),
    ]
