FROM python:3.12.2-alpine3.19

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /usr/app/

WORKDIR /usr/app/

COPY . /usr/app

COPY requirements.txt /usr/app

RUN pip install -r requirements.txt --no-cache-dir

EXPOSE 8000

CMD ["python", "manage.py", "runserver"]
