# Generated by Django 4.2.2 on 2023-07-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_remove_channel_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsubscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='channelsubscription',
            name='subscribing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribing', to='channel.channel'),
        ),
    ]
