# Generated by Django 4.2.2 on 2023-07-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channelsubscription_subscriber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='banner',
            new_name='banner_url',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='picture',
            new_name='picture_url',
        ),
    ]
