from django.urls import path

from apps.playlist import views

urlpatterns = [
    path(
        'own/',
        views.RetrieveOwnPlaylistsView.as_view(),
        name='own_playlists'
    ),
    path(
        'create/',
        views.CreatePlaylistView.as_view(),
        name='create_playlist'
    ),
    path(
        'channel/<int:channel_id>/',
        views.RetrieveChannelPlaylistsView.as_view(),
        name='channel_playlists'
    ),
    path(
        'video/<int:video_id>/video-saved/',
        views.RetrieveOwnPlaylistsToSaveVideo.as_view(),
        name='own_playlists_video_saved'
    ),
    path(
        '<int:playlist_id>/',
        views.RetrievePlaylistDetailsView.as_view(),
        name='playlist_details'
    ),
    path(
        '<int:playlist_id>/simple/',
        views.RetrieveSimplePlaylistView.as_view(),
        name='simple_playlist'
    ),
    path(
        '<int:playlist_id>/videos/',
        views.RetrieveVideosFromAPlaylistView.as_view(),
        name='videos_from_a_playlist'
    ),
    path(
        '<int:playlist_id>/save-video/',
        views.SaveVideoToPlaylistView.as_view(),
        name='save_video_to_playlist'
    ),
    path(
        '<int:playlist_id>/edit/',
        views.EditPlaylistView.as_view(),
        name='edit_playlist'
    ),
    path(
        '<int:playlist_id>/delete/',
        views.DeletePlaylistView.as_view(),
        name='delete_playlist'
    ),
    path(
        '<int:playlist_id>/video/<int:video_id>/remove/',
        views.RemoveVideoFromPlaylistView.as_view(),
        name='remove_video_from_playlist'
    ),
    path(
        '<int:playlist_id>/playlist-video/<int:playlist_video_id>/reposition/',
        views.RepositionPlaylistVideoView.as_view(),
        name='reposition_playlist_video'
    ),
]
