# Generated by Django 4.2.2 on 2023-07-02 19:05

import apps.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', apps.user.models.UserAccountManager()),
            ],
        ),
    ]
