# Generated by Django 4.2.2 on 2023-07-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_remove_channel_subscription_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='current_channel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.channel'),
        ),
    ]
