# Generated by Django 4.2.2 on 2023-07-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channelsubscription_subscriber_and_more'),
        ('user', '0002_useraccount_current_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='current_channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
        ),
    ]
