# Generated by Django 4.2.2 on 2023-07-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_useraccount_current_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='id_active',
            new_name='is_active',
        ),
    ]
