# Generated by Django 4.2.2 on 2023-07-02 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.URLField(blank=True, null=True, verbose_name='Picture or Avatar')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light')),
                ('languages', models.CharField(choices=[('ES', 'Spanish'), ('EN', 'English')], default='EN')),
            ],
        ),
    ]
