# Generated by Django 4.2.2 on 2023-07-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
