# Generated by Django 4.2.2 on 2023-07-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('video', '0002_videoview_video_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(related_name='video_views', through='video.VideoView', to='user_profile.profile'),
        ),
        migrations.CreateModel(
            name='LikedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(blank=True, default=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.profile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(related_name='video_likes', through='video.LikedVideo', to='user_profile.profile'),
        ),
    ]
