# Generated by Django 4.2.2 on 2023-07-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_remove_channel_subscription_and_more'),
        ('video', '0003_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedvideo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videoview',
            name='user',
        ),
        migrations.AddField(
            model_name='likedvideo',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.channel'),
        ),
        migrations.AddField(
            model_name='videoview',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(related_name='video_likes', through='video.LikedVideo', to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(related_name='video_views', through='video.VideoView', to='channel.channel'),
        ),
    ]
