# Generated by Django 4.2.2 on 2023-07-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channelsubscription_subscriber_and_more'),
        ('video', '0004_remove_likedvideo_user_remove_videoview_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedvideo',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
        ),
    ]
