# Generated by Django 4.2.2 on 2023-07-30 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_rename_banner_channel_banner_url_and_more'),
        ('video', '0005_alter_likedvideo_channel_alter_videoview_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoview',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='views', to='channel.channel'),
        ),
    ]
