# Generated by Django 4.2.2 on 2023-09-05 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_videoview_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoview',
            name='last_view_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
