# Generated by Django 4.2.2 on 2023-08-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_playlist_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'public'), ('PRI', 'private'), ('URL', 'only_url')], default='PRI', max_length=3),
        ),
    ]
