# Generated by Django 4.2.2 on 2023-08-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_playlist_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistvideo',
            options={'ordering': ['position']},
        ),
    ]
