# Generated by Django 4.2.2 on 2023-08-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_alter_playlistvideo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
