# Generated by Django 4.2.2 on 2023-08-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_alter_playlist_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['updated_at']},
        ),
    ]
