# Generated by Django 4.2.2 on 2023-08-24 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_alter_playlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='playlist',
            name='video_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail', to='playlist.playlistvideo'),
        ),
    ]
